version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  db:
    restart: always
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes: []  # Remove volume mounts for production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      target: production
    restart: always
    ports:
      - "80:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes: []  # Remove volume mounts for production

volumes:
  postgres_data_prod: